import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/api/api_exception.dart';
import '../../../core/di/providers.dart';
import '../../../core/widgets/app_state.dart';
import '../domain/game.dart';

class GamePage extends ConsumerStatefulWidget { const GamePage({super.key, required this.initial}); final Game initial; @override ConsumerState<GamePage> createState() => _GamePageState(); }
class _GamePageState extends ConsumerState<GamePage> with WidgetsBindingObserver {
  late Game _game; Timer? _timer; bool _sending = false; String? _error;
  @override void initState() { super.initState(); WidgetsBinding.instance.addObserver(this); _game = widget.initial; _startClock(); }
  @override void dispose() { WidgetsBinding.instance.removeObserver(this); _timer?.cancel(); super.dispose(); }
  @override void didChangeAppLifecycleState(AppLifecycleState state) { if (state == AppLifecycleState.resumed) _refresh(); }
  void _startClock() { _timer?.cancel(); if (_game.status != 'active') return; _timer = Timer.periodic(const Duration(seconds: 1), (_) { if (!mounted) return; if (_game.remaining <= 1) { _timer?.cancel(); _refresh(); } else { setState(() => _game = Game(id: _game.id, status: _game.status, stake: _game.stake, score: _game.score, remaining: _game.remaining - 1, title: _game.title, category: _game.category, level: _game.level)); } }); }
  Future<void> _refresh() async { try { final game = await ref.read(gameRepositoryProvider).get(_game.id); if (mounted) setState(() { _game = game; _error = null; _startClock(); }); } on ApiException catch (error) { if (mounted) setState(() => _error = error.message); } }
  Future<void> _choose(int choice) async { if (_sending || _game.remaining <= 0) return; setState(() { _sending = true; _error = null; }); try { final game = await ref.read(gameRepositoryProvider).choose(_game.id, choice); if (mounted) setState(() { _game = game; _startClock(); }); } on ApiException catch (error) { if (mounted) setState(() => _error = error.message); } finally { if (mounted) setState(() => _sending = false); } }
  Future<bool> _leave() async { if (_game.status != 'active') return true; final leave = await showDialog<bool>(context: context, builder: (context) => AlertDialog(title: const Text('تسيب المهمة؟'), content: const Text('لو سبتها مش هتظهر لك تاني.'), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('كمّل')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('سيبها'))])); if (leave == true) { await ref.read(gameRepositoryProvider).abandon(_game.id); return true; } return false; }
  @override Widget build(BuildContext context) { final level = _game.level; return PopScope(canPop: _game.status != 'active', onPopInvokedWithResult: (didPop, _) async { if (!didPop && await _leave() && context.mounted) context.pop(); }, child: Scaffold(appBar: AppBar(title: Text(_game.title), leading: IconButton(icon: const Icon(Icons.close), onPressed: () async { if (await _leave() && context.mounted) context.pop(); })), body: _game.status != 'active' ? AppStateView(icon: Icons.task_alt, message: _game.status == 'completed' ? 'المهمة خلصت. نتيجتك: ${_game.score}' : 'المهمة انتهت.', onRetry: () => context.go('/')) : level == null ? const AppStateView(message: 'تعذر تحميل المستوى.') : SafeArea(child: ListView(padding: const EdgeInsets.all(20), children: [Row(children: [Expanded(child: LinearProgressIndicator(value: level.number / 5)), const SizedBox(width: 12), Text('مستوى ${level.number}/5')]), const SizedBox(height: 18), Card(child: Padding(padding: const EdgeInsets.all(16), child: Row(children: [const Icon(Icons.timer_outlined), const SizedBox(width: 8), Text('الوقت: ${_game.remaining} ثانية'), const Spacer(), Text('نقاط: ${_game.score}')]))), const SizedBox(height: 22), Text(level.narrative, style: Theme.of(context).textTheme.titleLarge?.copyWith(height: 1.7)), const SizedBox(height: 30), ...level.choices.map((choice) => Padding(padding: const EdgeInsets.only(bottom: 12), child: OutlinedButton(onPressed: _sending || _game.remaining <= 0 ? null : () => _choose(choice.number), child: Padding(padding: const EdgeInsets.symmetric(vertical: 8), child: Text(choice.text, textAlign: TextAlign.center))))), if (_sending) const Center(child: Padding(padding: EdgeInsets.all(12), child: CircularProgressIndicator())), if (_error != null) Padding(padding: const EdgeInsets.only(top: 12), child: Text(_error!, textAlign: TextAlign.center, style: TextStyle(color: Theme.of(context).colorScheme.error))), if (_game.remaining == 0) const Padding(padding: EdgeInsets.only(top: 12), child: Text('انتهى الوقت، جاري تأكيد النتيجة من السيرفر...', textAlign: TextAlign.center))])))); }
}
