import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/api/api_exception.dart';
import '../../../core/di/providers.dart';
import '../../../core/widgets/app_state.dart';

final walletTransactionsProvider = FutureProvider<List<Map<String, dynamic>>>((ref) => ref.read(walletRepositoryProvider).transactions());
class WalletPage extends ConsumerWidget { const WalletPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final user = ref.watch(authProvider).value; final config = ref.watch(runtimeConfigProvider).value; final tx = ref.watch(walletTransactionsProvider); return Scaffold(appBar: AppBar(title: const Text('المحفظة')), floatingActionButton: FloatingActionButton.extended(onPressed: () => _showRequest(context, ref), icon: const Icon(Icons.add), label: const Text('طلب')), body: ListView(padding: const EdgeInsets.all(20), children: [Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('الرصيد المتاح'), Text('${user?.balance ?? 0} ${config?.coinName ?? ''}', style: Theme.of(context).textTheme.headlineMedium)])), const SizedBox(height: 18), Text('سجل العمليات', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 8), tx.when(loading: () => const Center(child: Padding(padding: EdgeInsets.all(32), child: CircularProgressIndicator())), error: (_, __) => AppStateView(message: 'تعذر تحميل سجل العمليات', onRetry: () => ref.invalidate(walletTransactionsProvider)), data: (items) => items.isEmpty ? const AppStateView(message: 'لسه مفيش عمليات في المحفظة.', icon: Icons.receipt_long_outlined) : Column(children: items.map((item) { final amount = item['amount'] as int; return Card(child: ListTile(leading: Icon(amount >= 0 ? Icons.add_circle_outline : Icons.remove_circle_outline, color: amount >= 0 ? Colors.greenAccent : Colors.orangeAccent), title: Text(item['description_ar'] as String), subtitle: Text(item['created_at'] as String), trailing: Text('${amount > 0 ? '+' : ''}$amount'))); }).toList()))])); }
  Future<void> _showRequest(BuildContext context, WidgetRef ref) async { final amount = TextEditingController(); final reference = TextEditingController(); bool withdraw = false; final result = await showDialog<bool>(context: context, builder: (dialog) => StatefulBuilder(builder: (context, setState) => AlertDialog(title: Text(withdraw ? 'طلب سحب' : 'طلب إيداع'), content: Column(mainAxisSize: MainAxisSize.min, children: [SwitchListTile(value: withdraw, onChanged: (value) => setState(() => withdraw = value), title: const Text('طلب سحب بدل إيداع')), TextField(controller: amount, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'عدد العملات')), const SizedBox(height: 12), TextField(controller: reference, decoration: const InputDecoration(labelText: withdraw ? 'وسيلة الاستلام' : 'مرجع التحويل'))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('إلغاء')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('إرسال'))]))); if (result != true) return; try { final value = int.parse(amount.text); if (withdraw) { await ref.read(walletRepositoryProvider).withdrawal(value, reference.text.trim()); } else { await ref.read(walletRepositoryProvider).deposit(value, reference.text.trim()); } ref.invalidate(walletTransactionsProvider); if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('تم إرسال الطلب للمراجعة.'))); } on FormatException { if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('اكتب رقم صحيح.'))); } on ApiException catch (error) { if (context.mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(error.message))); } finally { amount.dispose(); reference.dispose(); } }
}
