import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/api/api_exception.dart';
import '../../../core/di/providers.dart';
import '../../game/domain/game.dart';

class HomePage extends ConsumerStatefulWidget { const HomePage({super.key}); @override ConsumerState<HomePage> createState() => _HomePageState(); }
class _HomePageState extends ConsumerState<HomePage> { int _stake = 50; bool _loading = false; String? _message;
  Future<void> _start() async { setState(() { _loading = true; _message = null; }); try { final game = await ref.read(gameRepositoryProvider).start(_stake); if (mounted) context.push('/game', extra: game); } on ApiException catch (error) { if (mounted) setState(() => _message = error.message); } finally { if (mounted) setState(() => _loading = false); } }
  Future<void> _resume() async { setState(() { _loading = true; _message = null; }); try { final game = await ref.read(gameRepositoryProvider).resume(); if (mounted) context.push('/game', extra: game); } on ApiException catch (error) { if (mounted) setState(() => _message = error.message); } finally { if (mounted) setState(() => _loading = false); } }
  @override Widget build(BuildContext context) { final user = ref.watch(authProvider).value; final config = ref.watch(runtimeConfigProvider).value; final values = [50, 100, 250, 500, 1000].where((value) => config == null || (value >= config.minStake && value <= config.maxStake)).toList(); return Scaffold(appBar: AppBar(title: const Text('غرفة العمليات'), actions: [IconButton(onPressed: () => context.push('/profile'), icon: const Icon(Icons.person_outline))]), body: RefreshIndicator(onRefresh: () => ref.read(authProvider.notifier).refreshUser(), child: ListView(padding: const EdgeInsets.all(20), children: [Text('أهلاً ${user?.displayName ?? ''}', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 16), Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('رصيدك المتاح'), const SizedBox(height: 6), Text('${user?.balance ?? 0} ${config?.coinName ?? ''}', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 12), OutlinedButton.icon(onPressed: () => context.push('/wallet'), icon: const Icon(Icons.account_balance_wallet_outlined), label: const Text('المحفظة'))])), const SizedBox(height: 24), Text('ابدأ مهمة', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 8), const Text('القصة بتتختار عشوائي من قصص جديدة عليك فقط.'), const SizedBox(height: 14), Wrap(spacing: 8, runSpacing: 8, children: values.map((value) => ChoiceChip(label: Text('$value'), selected: _stake == value, onSelected: _loading ? null : (_) => setState(() => _stake = value))).toList()), const SizedBox(height: 20), ElevatedButton.icon(onPressed: _loading ? null : _start, icon: const Icon(Icons.play_arrow_rounded), label: const Text('ابدأ اللعبة')), TextButton(onPressed: _loading ? null : _resume, child: const Text('استكمل لعبة متوقفة')), if (_message != null) Padding(padding: const EdgeInsets.only(top: 12), child: Text(_message!, textAlign: TextAlign.center, style: TextStyle(color: Theme.of(context).colorScheme.error))), const SizedBox(height: 36), const Card(child: Padding(padding: EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('نظام آمن'), SizedBox(height: 6), Text('كل مستوى له وقت محدد، والنتيجة بتتسجل من السيرفر. مفيش قصص مكررة ولا ألعاب مجانية.')])))])); }
}
