import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/di/providers.dart';
import '../../../core/widgets/app_state.dart';

final gameHistoryProvider = FutureProvider<List<Map<String, dynamic>>>((ref) async => ((await ref.read(apiProvider).get('/games/history'))['items'] as List).map((entry) => Map<String, dynamic>.from(entry as Map)).toList());
final notificationsProvider = FutureProvider<List<Map<String, dynamic>>>((ref) async => ((await ref.read(apiProvider).get('/notifications'))['items'] as List).map((entry) => Map<String, dynamic>.from(entry as Map)).toList());
class HistoryPage extends ConsumerWidget { const HistoryPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final data = ref.watch(gameHistoryProvider); return Scaffold(appBar: AppBar(title: const Text('سجل الألعاب')), body: data.when(loading: () => const Center(child: CircularProgressIndicator()), error: (_, __) => AppStateView(message: 'تعذر تحميل سجل الألعاب', onRetry: () => ref.invalidate(gameHistoryProvider)), data: (items) => items.isEmpty ? const AppStateView(message: 'لسه ما لعبتش أي مهمة.', icon: Icons.history) : ListView(padding: const EdgeInsets.all(16), children: items.map((item) => Card(child: ListTile(title: Text(item['title_ar'] as String), subtitle: Text(item['created_at'] as String), trailing: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Text(item['status'] as String), Text('نقاط: ${item['score']}')]))).toList()))); }
}
class NotificationsPage extends ConsumerWidget { const NotificationsPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final data = ref.watch(notificationsProvider); return Scaffold(appBar: AppBar(title: const Text('الإشعارات')), body: data.when(loading: () => const Center(child: CircularProgressIndicator()), error: (_, __) => AppStateView(message: 'تعذر تحميل الإشعارات', onRetry: () => ref.invalidate(notificationsProvider)), data: (items) => items.isEmpty ? const AppStateView(message: 'مفيش إشعارات جديدة.', icon: Icons.notifications_none) : ListView(padding: const EdgeInsets.all(16), children: items.map((item) => Card(child: ListTile(leading: const Icon(Icons.notifications_outlined), title: Text(item['title_ar'] as String), subtitle: Text(item['body_ar'] as String))).toList()))); }
}
class InformationPage extends StatelessWidget { const InformationPage({super.key, required this.title, required this.body, required this.icon}); final String title; final String body; final IconData icon; @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(title)), body: AppStateView(message: body, icon: icon)); }
